# Generated by Django 4.2.4 on 2023-08-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='findItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='img/')),
                ('Name', models.CharField(max_length=70)),
                ('Price', models.CharField(max_length=70)),
                ('Place', models.TextField(blank=True)),
            ],
        ),
    ]
